language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
script: bash -c '. .travis-ocaml.sh && . launch-learn-ocaml.sh'
env:
  - OCAML_VERSION="4.03"
